#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
LD = g++

INC = 
CFLAGS = -g
#CFLAGS = -Wall -fexceptions -g
OUTPUT_BIN_DIR = bin
SRC_DIR = src

all: rsgeotools

clean: 
	rm -rf bin

before_rsgeotools: 
	test -d bin || mkdir -p bin

rsgeotools: before_rsgeotools rsgeotools-conv rsgeotools-csv2rvtdata rsgeotools-tiffcompose rsgeotools-o5m-get-outlines rsgeotools-tilepacker

rsgeotools-conv: before_rsgeotools  
	$(CXX) $(CFLAGS) $(INC) $(SRC_DIR)/conv/conv.cpp -o $(OUTPUT_BIN_DIR)/rsgeotools-conv

rsgeotools-csv2rvtdata: before_rsgeotools  
	$(CXX) $(CFLAGS) $(INC) -I$(SRC_DIR)/csv2rvtdata/ -lgeos_c $(SRC_DIR)/csv2rvtdata/csv.c $(SRC_DIR)/csv2rvtdata/csv2rvtdata.cpp -o $(OUTPUT_BIN_DIR)/rsgeotools-csv2rvtdata

rsgeotools-tiffcompose: before_rsgeotools  
	$(CXX) $(CFLAGS) $(INC) $(SRC_DIR)/tiffcompose/tiffcompose.cpp -ltiff -o $(OUTPUT_BIN_DIR)/rsgeotools-tiffcompose
	
rsgeotools-o5m-get-outlines: before_rsgeotools  
	$(CC) $(CFLAGS) $(INC) $(SRC_DIR)/o5m_get_outlines/o5m_get_outlines.c -o $(OUTPUT_BIN_DIR)/rsgeotools-o5m-get-outlines
	
rsgeotools-tilepacker: before_rsgeotools  
	$(CXX) $(CFLAGS) $(INC) $(SRC_DIR)/tilepacker/tilepacker.cpp -lz -lbz2 -o $(OUTPUT_BIN_DIR)/rsgeotools-tilepacker

.PHONY: before_rsgeotools clean_rsgeotools

