#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
LD = g++

INC = 
CFLAGS = -Wall -fexceptions -g
OUTPUT_BIN_DIR = bin
SRC_DIR = src

all: rsgeotools

clean: 
	rm -rf bin

before_rsgeotools: 
	test -d bin || mkdir -p bin

rsgeotools: before_rsgeotools rsgeotools-conv

rsgeotools-conv: before_rsgeotools  
	$(CXX) $(CFLAGS) $(INC) $(SRC_DIR)/rsgeotools-conv.cpp -o $(OUTPUT_BIN_DIR)/rsgeotools-conv

.PHONY: before_rsgeotools clean_rsgeotools

